apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tickets
  labels:
    cloud.googleapis.com/location: REGION
spec:
  template:
    spec:
      serviceAccountName: SERVICE_ACCOUNT
      containers:
        - image: IMAGE
          args:
            - -firebase-project-id=PROJECT_ID
            - -env=development
